---
title: "balancing"
output: html_document
---

```{r}
library(haven)
library(ggplot2)
#library(mgcv)
library(Matching)
library(xtable)
library(dplyr)
library(cobalt)
library(MatchIt)

```


```{r}
debit = read_dta("data/debitcard199598.dta")
```

```{r}
#Clean
any(unlist(lapply(debit,FUN=function(x){any(is.na(x))})))

debit = debit %>%
  mutate(num_of_earners = as.factor(num_of_earners)) %>%
  mutate(family_size = as.factor(family_size)) %>%
  mutate(average_age = factor(average_age, labels = c("<30", "31-40", "41-50", "51-65", "65+")))  %>%
  mutate(geograph_area = factor(geograph_area, labels = c("North", "Central Italy", "South and Islands"))) %>%
  mutate(num_of_inhabitants = factor(num_of_inhabitants, labels = c("<20k", "20-40k", "40-500k", "500k+"))) %>%
  mutate(householder_age = factor(householder_age, labels = c("<30", "31-40", "41-50", "51-65", "65+"))) %>%
  mutate(householder_education = factor(householder_education, labels = c("None", "Elementary", "Middle School", "High School", "Bachelors", "Post-Graduate"))) %>%
  mutate(debit_card1998 = as.factor(debit_card1998))


#Continuous Variables
names(which(unlist(lapply(debit,class))=="numeric"))

#Categorical Variables
names(which(unlist(lapply(debit,class))=="factor"))

n_indi<-c(which(unlist(lapply(debit,class))=="numeric"))
c_indi<-c(which(unlist(lapply(debit,class))=="factor"))

#Descriptive Comparison
data_t<-subset(debit,debit_card1998==1)
data_c<-subset(debit,debit_card1998==0)
size_t<-dim(data_t)[1]
size_c<-dim(data_c)[1]

debit$debit_card1998 = as.integer(debit$debit_card1998)
debit$debit_card1998 = debit$debit_card1998 - 1
```

```{r}
#Calculate ASD for Continuous Variables
dif1<-apply(data.matrix(data_t[,n_indi]),2,mean)-
  apply(data.matrix(data_c[,n_indi]),2,mean)

sd1<-sqrt(apply(data.matrix(data_t[,n_indi]),2,var)/size_t+
      apply(data.matrix(data_c[,n_indi]),2,var)/size_c)

ASD_1<-dif1/sd1;boxplot(ASD_1)

ASD<-data.frame(mean=dif1,sd=sd1,asd=ASD_1)

pdf("asd.pdf",width=8,height=6)
ggplot(data=ASD,aes(x=names(ASD_1),y=asd,ymin=asd,ymax=asd))+geom_pointrange()+
  geom_hline(yintercept = 0,lty=2)+coord_flip()+xlab("Variables")+ylab("Standardized Difference")
dev.off()

model_control<-lm(spending1998 ~ spending1995 + num_of_earners + average_age + family_size + geograph_area + num_of_inhabitants + householder_age + householder_education + num_of_banks + interest_rate + income + wealth + cash_inventory, data=data_c)
                  
model_treated<-lm(spending1998 ~ spending1995 + num_of_earners + average_age + family_size + geograph_area + num_of_inhabitants + householder_age + householder_education + num_of_banks + interest_rate + income + wealth + cash_inventory, data=data_t)


ATE_1<-(sum(data_t$spending1998-predict(model_control,newdata = data_t,type="response"))-
  sum(data_c$spending1998-predict(model_treated,newdata = data_c,type="response")))/dim(debit)[1]


ATT_1<-mean(data_t$spending1998-predict(model_control,newdata = data_t,type="response"))

```

```{r}
#PS Histogram

first_model = glm(debit_card1998 ~ spending1995 + num_of_earners + average_age + family_size + geograph_area +  num_of_inhabitants + householder_age + householder_education + num_of_banks + interest_rate + income + wealth + cash_inventory, family = binomial(link="logit"), data = debit)

debit.ps = debit
debit.ps$ps = fitted(first_model)

a<-hist(debit.ps$ps[which(debit.ps$debit_card1998==0)],breaks=50,freq=FALSE)
a$counts<-a$counts/sum(a$counts)

b<-hist(debit.ps$ps[which(debit.ps$debit_card1998==1)],breaks=50,add=T)
b$counts<-b$counts/sum(b$counts)

pdf("prophist.pdf",width=8,height=6)
plot(a,col=rgb(1,0,0,0.5),main="Overlap Check",cex.main=0.9,xlab="Estimated Propensity Score",ylab="Density",xlim=c(0,1))
plot(b,add=TRUE,col=rgb(0,0,1,0.5),main="Overlap Check",xlab="Estimated Propensity Score",ylab="Density")
legend("topright",legend=c("Control Group","Treatment Group"),col=c("red","blue"),pch=15,cex=0.7)
dev.off()

################################################
#  Exclude samples in nonoverlapping region   ##
################################################ 
low_bound<-max(min(debit.ps$ps[which(debit.ps$debit_card1998==1)]),
               min(debit.ps$ps[which(debit.ps$debit_card1998==0)]))

up_bound<-min(max(debit.ps$ps[which(debit.ps$debit_card1998==1)]),
              max(debit.ps$ps[which(debit.ps$debit_card1998==0)]))

#Disgard the sample out of the common support
olp.debit<-subset(debit.ps,debit.ps$ps>=low_bound&debit.ps$ps<=up_bound)
```


```{r}
#PS Matching
olp.debit$debit_card1998 = as.integer(olp.debit$debit_card1998)
olp.debit$debit_card1998 = olp.debit$debit_card1998 - 1
olp.debit$debit_card1998 = as.logical(olp.debit$debit_card1998)

ATE_matching_m<-Match(Y=olp.debit$spending1998,Tr=olp.debit$debit_card1998,estimand = "ATE",
                  X=data.matrix(olp.debit[,-c(1,2,16)]),M=6,Weight = 1)

ATT_matching_m<-Match(Y=olp.debit$spending1998,Tr=olp.debit$debit_card1998,estimand = "ATT",
                      X=data.matrix(olp.debit[,-c(1,2,16)]),M=6,Weight = 1)


#Balance Check: defends on the method#
######################################
treated<-unique(ATT_matching_m$index.treated)
control<-ATT_matching_m$index.control
treat_size<-length(treated)
control_size<-dim(olp.debit)[1]-treat_size


debit$debit_card1998 = as.integer(debit$debit_card1998)

#ASD: absolute standardized difference. original data
ori_d<-apply(data.matrix(debit[,-c(1,2)]),MARGIN=2,FUN=function(x){
  abs(mean(x[debit$debit_card1998==1])-mean(x[debit$debit_card1998==0]))})


sd<-apply(data.matrix(debit[,-c(1,2)]),MARGIN=2,FUN=function(x)
{sqrt(var(x[debit$debit_card1998==1])/sum(debit$debit_card1998)+var(x[debit$debit_card1998==0])/sum(1-debit$debit_card1998))})

ori_asd<-ori_d/sd

olp_sd<-apply(data.matrix(olp.debit[,-c(1,2,16)]),MARGIN=2,FUN=function(x)
{sqrt(var(x[treated])/treat_size+var(x[-treated])/control_size)})

#ASD: matching  

match_d<-apply(data.matrix(olp.debit[,-c(1,2,16)]),MARGIN=2,FUN=function(x)
{abs(mean(x[treated])-mean(x[control]))})
match_asd<-match_d/olp_sd


#ASD: weighting
ipw<-olp.debit$ps/(1-olp.debit$ps)
ipw_d<-apply(data.matrix(olp.debit[,-c(1,2,16)]),MARGIN=2,FUN=function(x){
  abs(mean(x[treated])-sum(x[-treated]*ipw[-treated])/
        sum(ipw[-treated]))})
weight_asd<-ipw_d/olp_sd



###########################################
#ASD Comparison between methods: boxplot  #
###########################################
pdf("ASD_compare.pdf",width=8,height=6)
boxplot(ori_asd,weight_asd,match_asd,main="ASD for Different Methods",names=c("original","weighting","matching"),
        ylab="Abs Standardized Difference")
dev.off()

```


```{r}
############################################
#Regression Adjustment 2: on Matched Sample#
############################################

##############################################################
### need to re-fit the regression model to the matched sample#
##############################################################

#model_control_m<-glm(outcomeformula, data=data_c,family=binomial(link="logit"))
#model_treated_m<-glm(outcomeformula, data=data_t,family=binomial(link="logit"))


#ATT
mu1=predict(model_control,newdata=olp.debit[control,],type="response")
mu2=predict(model_control,newdata=olp.debit[ATT_matching_m$index.treated,],type="response")

ATT_mix=mean(olp.debit[treated,]$spending1998)-sum(olp.debit[control,]$spending1998+mu2-mu1)/(6*treat_size)


#ATE
mu3=predict(model_control,newdata=olp.debit[ATE_matching_m$index.control,],type="response")
mu4=predict(model_control,newdata=olp.debit[ATE_matching_m$index.treated,],type="response")
mu5=predict(model_treated,newdata=olp.debit[ATE_matching_m$index.control,],type="response")
mu6=predict(model_treated,newdata=olp.debit[ATE_matching_m$index.treated,],type="response")

ATE_mix=ATE_matching_m$est-(-sum(mu3)+sum(mu4)-sum(mu5)+sum(mu6))/(6*dim(olp.debit)[1])
```

```{r}
#Cobalt

#weight
debit.weighted = bal.tab(olp.debit[,-c(1,2,16)], treat = olp.debit$debit_card1998, method = "weighting", weights = ipw, estimand = "ATT")
love.plot(debit.weighted)


#Nearest Neighbor 2:1 Matching
match.out = matchit(f.build("debit_card1998", olp.debit), data = olp.debit, method = "nearest", 
                 ratio = 1,  replace = TRUE)
debit.matched = bal.tab(match.out)

love.plot(debit.matched)
```

